---
- hosts: all
  become: true
  vars_files:
  - vars/liste_services.yml
  tasks:

  - name: installer le service de "{{ service['db']['name'] }}"
    apt:
      name: "{{ service['db']['rpm'] }}"
      state: latest
    when:
    - type == "db"
    - ansible_distribution == "Ubuntu"

  - name: installer le service web
    yum:
      name: "{{ service['web']['rpm'] }}"
      state: latest
    when:
    - type == "web"
    - ansible_distribution == "CentOS"
