---
- name: Deploiment de l'application wordporess
  hosts: app1
  become: yes
  tasks:
  - name: Unarchive a file that needs to be downloaded (added in 2.0)
    unarchive:
      src: https://wordpress.org/latest.tar.gz
      dest: /var/www/html/
      remote_src: yes
      mode: 0755
      owner: apache
      group: apache
